# Generated by Django 4.1.4 on 2022-12-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemodel",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
    ]
